name: Set up environment
description: Common environment setup steps for this repository

inputs:
  brew:
    description: Set up Homebrew
    default: 'false'
    # Only some runners need this, for example see:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#homebrew-note
  ktfmt:
    description: Set up ktfmt
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up Homebrew
      if: ${{ inputs.brew == 'true' || inputs.ktfmt == 'true' }}
      run: ./.github/actions/setup-environment/setup-homebrew.sh
      shell: bash
    - name: Set up ktfmt
      if: ${{ inputs.ktfmt == 'true' }}
      run: brew install ktfmt
      shell: bash
