name: Set up environment
description: Common environment setup steps for this repository

inputs:
  jdk:
    description: Set up JDK
    default: 'false'
  gradle:
    description: Set up Gradle
    default: 'false'
  brew:
    description: Set up Homebrew
    default: 'false'
    # Only some runners need this, for example see:
    # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#homebrew-note
  ktfmt:
    description: Set up ktfmt
    default: 'false'
  hardware-acceleration:
    description: Enable hardware acceleration needed to run for example an Android emulator
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up JDK
      if: ${{ inputs.jdk == 'true' || inputs.gradle == 'true' }}
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version-file: '.java-version'
        distribution: 'temurin'
        # Using 'temurin' speeds up the job, because this distribution is cached by the runner.
        # See: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
    - name: Set up Gradle
      if: ${{ inputs.gradle == 'true' }}
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
    - name: Set up Homebrew
      if: ${{ inputs.brew == 'true' || inputs.ktfmt == 'true' }}
      run: ./.github/actions/setup-environment/setup-homebrew.sh
      shell: bash
    - name: Set up ktfmt
      if: ${{ inputs.ktfmt == 'true' }}
      run: brew install ktfmt
      shell: bash
    - name: Enable KVM group perms
      if: ${{ inputs.hardware-acceleration == 'true' }}
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash
